name: Waka Readme

on:
  schedule:
<<<<<<< HEAD
    # Runs at 12am IST
    - cron: '30 180 * * *'
||||||| 6eac042... Update update-readme.yml
    # Runs at 12am UTC
    - cron: '0 0 * * *'
=======
    # Runs at 12am IST
    - cron: '30 18 * * *'
>>>>>>> parent of 6eac042... Update update-readme.yml

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: jcalaunan/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
<<<<<<< HEAD
          SHOW_PROJECTS: "false"
          SHOW_LINES_OF_CODE: "true"
          LOCALE: "en"
||||||| 6eac042... Update update-readme.yml
          SHOW_PROJECTS: "False"
          SHOW_LINES_OF_CODE: "True"
          LOCALE: "en"
=======
>>>>>>> parent of 6eac042... Update update-readme.yml
